# Dependencies
gems:             [jekyll-paginate, jekyll-gist]
markdown:         kramdown
kramdown:
  input:          GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            FLIMfit
tagline:          'FLIM analysis'
description:      'A state of the art open source FLIM analysis package'
url:              http://127.0.0.1/
baseurl:          /

author:
  name:           'Sean Warren'
  url:            https://github.com/seanwarren

paginate:         5
paginate_path:    "/news/page:num/"

# Custom vars
version:          4.11.2

links:
   mailing-list:  http://lists.openmicroscopy.org.uk/mailman/listinfo/flimfit-users/
   downloads:     http://downloads.openmicroscopy.org/latest/flimfit/
   docs:          http://docs.flimfit.org/

github:
  repo:           https://github.com/imperial-photonics/FLIMfit/

page_gen-dirs:    true

page_gen:
 - data:          'downloads'
   name:          'version'
   dir:           'downloads'
